### ISSUE TITLE
Move Datasets::TLC from red-data-tools/red-datasets to here

### ISSUE THREAD

**Issue by kou** [red-data-tools/red-datasets-parquet#1]
See also: https://github.com/red-data-tools/red-datasets/issues/152

Cc: @otegami

**Comment by otegami** [comment]
## What we will need to do
- [x] The rest datasets about  NYC Taxi and Limousine Commission haven't been implemented yet.
    - FHV Trips Data
    - High Volume FHV Trips Data
^ We will deal with it [here](https://github.com/red-data-tools/red-datasets-parquet/issues/8)

- [x] We will have to delete Datasets::TLC in red-data-tools/red-datasets.
    - Because We have already moved Datasets::TLC from red-data-tools/red-datasets to here.
    - ^ fixed: https://github.com/red-data-tools/red-datasets/pull/154

**Comment by otegami** [comment]
I think we have done this issue. May I closed it?

**Comment by kou** [comment]
Sure.
