### ISSUE TITLE
How about using `Datasets::` not `DatasetsParquet::` for dataset?

### ISSUE THREAD

**Issue by kou** [red-data-tools/red-datasets-parquet#9]
e.g.: `DatasetsParquet::TLC::GreenTaxiTrip` -> `Datasets::TLC::GreenTaxiTrip`

If we use `Datasets::` for each dataset, users don't need to care whether the dataset uses Apache Parquet or not.

**Comment by otegami** [comment]
Thank you for your advice. I will rename it!

**Comment by otegami** [comment]
I fixed it in https://github.com/red-data-tools/red-datasets-parquet/pull/10 🙏
